export const projectAssets: Record<string, string[]> = {
  shanhe: [
    '/assets/ITGM405/ITGM405.png',
    '/assets/ITGM405/ITGM405_s1_milestone.png',
    '/assets/ITGM405/ITGM405_s2_milestone.png',
    '/assets/ITGM405/ITGM405_s3_milestone.png',
    '/assets/ITGM405/ITGM405_s4_milestone.png',
    '/assets/ITGM405/ITGM405_s5_milestone.png',
    '/assets/ITGM405/ITGM405_s6_milestone.png',
    '/assets/ITGM405/shanhe-npc.png',
    '/assets/ITGM405/shanhe-npc-2.png',
    '/assets/ITGM405/shanhe-quest-ui.png',
    '/assets/ITGM405/ITGM405_MoneyShot_4.png',
  ],
  'bubono-bumperland': [
    '/assets/ITGM475/bubono-3.png',
    '/assets/ITGM475/bubono-windmill-arena.jpg',
    '/assets/ITGM475/bubono-1.png',
    '/assets/ITGM475/bubono-2.png',
    '/assets/ITGM475/bubono-5.png',
    '/assets/ITGM475/bubono-7.png',
    '/assets/ITGM475/bubono-11.png',
    '/assets/ITGM475/bubono-asset-logo.png',
    '/assets/ITGM475/bubono-prop-bomb.png',
    '/assets/ITGM475/bubono-enemy-worm.png',
  ],
  'stairs-in-the-woods': [
    'https://drive.google.com/thumbnail?id=1OwzwHoIYtFThl5p1Ee4Su38DXczQcYn-&sz=w2000',
    'https://drive.google.com/thumbnail?id=1IIPLNuUsfvHcDY8dMvEU17MNF3Q5J65h&sz=w2000',
    'https://drive.google.com/thumbnail?id=1O5-caECe9dL2Q_-u7Qk-Z1L9mvNXkhh2&sz=w2000',
  ],
  'castle-defense': [
    'https://drive.google.com/thumbnail?id=1iRz1n3k14Pl7So9Z639bcMF3bTXxu21g&sz=w2000',
    'https://drive.google.com/thumbnail?id=1Km8T5iAP_y_jTkzFoQYPFavDvmEz1BhC&sz=w2000',
  ],
  'bio-lab': [
    'https://drive.google.com/thumbnail?id=1YG62TLXBIErn6AAwMpl4fBqyudK4pBfL&sz=w2000',
    'https://drive.google.com/thumbnail?id=161Sg3C2TZ2cywWP2cNEkzxfKzEvfbnKP&sz=w2000',
    'https://drive.google.com/thumbnail?id=1Mamy5hLfhEcxA480AC48fokRdE4tILoF&sz=w2000',
    'https://drive.google.com/thumbnail?id=1ba6qTK5NyVKPHmVzb1oc62PHKyYYg-Gb&sz=w2000',
  ],
  aukadyssey: [
    '/assets/ITGM356/ITGM356.png',
    '/assets/ITGM356/ITGM356-1.png',
    '/assets/ITGM356/ITGM356-2.png',
    '/assets/ITGM356/ITGM356-3.png',
    '/assets/ITGM356/ITGM356-4.png',
    '/assets/ITGM356/ITGM356-5.png',
    '/assets/ITGM356/aukadyssey-pip.png',
    '/assets/ITGM356/aukadyssey-background.png',
    '/assets/ITGM356/aukadyssey-level-plan.png',
    '/assets/ITGM356/aukadyssey-map.png',
  ],
  ink: [
    '/assets/Ink/ScreenShot00005.png',
    '/assets/Ink/ScreenShot00006.png',
    '/assets/Ink/ScreenShot00007.png',
    '/assets/Ink/ScreenShot00008.png',
    '/assets/Ink/ScreenShot00009.png',
    '/assets/Ink/ScreenShot00010.png',
    '/assets/Ink/ink-level-l1.png',
    '/assets/Ink/ink-character-idle.png',
    '/assets/Ink/ink-boss.png',
    '/assets/Ink/ink-ui-mark.png',
    '/assets/Ink/ink-thumbnail.png',
  ],
  eshaver: [
    '/assets/UXDG360/es-home.png',
    '/assets/UXDG360/es-product.png',
    '/assets/UXDG360/es-product2.png',
    '/assets/UXDG360/es-product3.png',
    '/assets/UXDG360/es-cards.png',
    '/assets/UXDG360/mockup-floating-macbook.png',
    '/assets/UXDG360/mockup-imac-silver.png',
    '/assets/UXDG360/mockup-retina-imac.png',
    '/assets/UXDG360/mockup-imac-pro.png',
  ],
  terradotta: [
    '/assets/TerraDotta/journey.png',
    '/assets/TerraDotta/prekickoff.png',
    '/assets/TerraDotta/research.png',
    '/assets/TerraDotta/affinity.png',
    '/assets/TerraDotta/brainstorm.png',
    '/assets/TerraDotta/midpoint.png',
  ],
}
