export const projectAssets: Record<string, string[]> = {
  'pubg-signal-wheel': [
    '/assets/projects/pubg-signal-wheel/pubg-signal-wheel.svg',
  ],
  shanhe: [
    '/assets/projects/shanhe/ITGM405.webp',
    '/assets/projects/shanhe/ITGM405_s1_milestone.webp',
    '/assets/projects/shanhe/ITGM405_s2_milestone.webp',
    '/assets/projects/shanhe/ITGM405_s3_milestone.webp',
    '/assets/projects/shanhe/ITGM405_s4_milestone.webp',
    '/assets/projects/shanhe/ITGM405_s5_milestone.webp',
    '/assets/projects/shanhe/ITGM405_s6_milestone.webp',
    '/assets/projects/shanhe/shanhe-npc.webp',
    '/assets/projects/shanhe/shanhe-npc-2.webp',
    '/assets/projects/shanhe/shanhe-quest-ui.webp',
    '/assets/projects/shanhe/ITGM405_MoneyShot_4.webp',
  ],
  'bubono-bumperland': [
    '/assets/projects/bubono-bumperland/bubono-3.webp',
    '/assets/projects/bubono-bumperland/bubono-windmill-arena.webp',
    '/assets/projects/bubono-bumperland/bubono-1.webp',
    '/assets/projects/bubono-bumperland/bubono-2.webp',
    '/assets/projects/bubono-bumperland/bubono-5.webp',
    '/assets/projects/bubono-bumperland/bubono-7.webp',
    '/assets/projects/bubono-bumperland/bubono-11.webp',
    '/assets/projects/bubono-bumperland/bubono-asset-logo.webp',
    '/assets/projects/bubono-bumperland/bubono-prop-bomb.webp',
    '/assets/projects/bubono-bumperland/bubono-enemy-worm.webp',
  ],
  aukadyssey: [
    '/assets/projects/aukadyssey/ITGM356.webp',
    '/assets/projects/aukadyssey/ITGM356-1.webp',
    '/assets/projects/aukadyssey/ITGM356-2.webp',
    '/assets/projects/aukadyssey/ITGM356-3.webp',
    '/assets/projects/aukadyssey/ITGM356-4.webp',
    '/assets/projects/aukadyssey/ITGM356-5.webp',
    '/assets/projects/aukadyssey/aukadyssey-pip.webp',
    '/assets/projects/aukadyssey/aukadyssey-background.webp',
    '/assets/projects/aukadyssey/aukadyssey-level-plan.webp',
    '/assets/projects/aukadyssey/aukadyssey-map.webp',
  ],
  ink: [
    '/assets/projects/ink/ScreenShot00005.webp',
    '/assets/projects/ink/ScreenShot00006.webp',
    '/assets/projects/ink/ScreenShot00007.webp',
    '/assets/projects/ink/ScreenShot00008.webp',
    '/assets/projects/ink/ScreenShot00009.webp',
    '/assets/projects/ink/ScreenShot00010.webp',
    '/assets/projects/ink/ink-level-l1.webp',
    '/assets/projects/ink/ink-character-idle.webp',
    '/assets/projects/ink/ink-boss.webp',
    '/assets/projects/ink/ink-ui-mark.webp',
    '/assets/projects/ink/ink-thumbnail.webp',
  ],
  eshaver: [
    '/assets/projects/eshaver/es-home.webp',
    '/assets/projects/eshaver/es-product.webp',
    '/assets/projects/eshaver/es-product2.webp',
    '/assets/projects/eshaver/es-product3.webp',
    '/assets/projects/eshaver/es-cards.webp',
    '/assets/projects/eshaver/mockup-floating-macbook.webp',
    '/assets/projects/eshaver/mockup-imac-silver.webp',
    '/assets/projects/eshaver/mockup-retina-imac.webp',
    '/assets/projects/eshaver/mockup-imac-pro.webp',
  ],
  terradotta: [
    '/assets/projects/terradotta/journey.webp',
    '/assets/projects/terradotta/prekickoff.webp',
    '/assets/projects/terradotta/research.webp',
    '/assets/projects/terradotta/affinity.webp',
    '/assets/projects/terradotta/brainstorm.webp',
    '/assets/projects/terradotta/midpoint.webp',
  ],
}
